version: '3'

services:
  app:
    container_name: api-boilerplate
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    command: npm run start:dev
    networks:
      - test-net

  mydb:
    restart: always
    image: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      $POSTGRES_USER: postgres
      $POSTGRES_PASSWORD: postgres
      $POSTGRES_DB: data
    ports:
      - 5433:5432/tcp
    networks:
      - test-net

  pgadmin:
    restart: always
    container_name: api-boilerplate-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - test-net

networks:
  test-net:
    driver: bridge

volumes:
  pgadmin:
    driver: local
  db-data:
    driver: local
